---
- name: Trabalhando com templates
  hosts: localhost
  tasks:
    - name: Criando o template
      ansible.builtin.template:
        src : ./exemplo-template-simples.j2
        dest: /home/arlindo/aula/ansible/exemplo.txt



#Comando usado no terminal:

#ansible-playbook playbook-template-simples.yaml --extra-vars="@variaveis.yaml"
