---
- name: Exibindo exemplo com variáveis
  hosts: localhost
  tasks:
    - name: Exibir mensagem
      ansible.builtin.debug:
        msg: "Fala aí {{ nome}}, blz ?"

#Outra forma é passar a variável diretamente na linha de comando. Apaga a referência do playbook e na linha de comando passa o comando abaixo:
#ansible-playbook variaveis_playbook.yaml --extra-vars "nome=José"